### ISSUE TITLE
SN_PatchGAN

### ISSUE THREAD

**Issue by s86707** [JerrySchonenberg/CloudGAN#4]
Hi, 

i'm using the SN_PatchGAN to run the CloudGAN-Code but i don't get the same good results as you have shown. 
This is my command: 

python -m CloudGAN --img project/input/sample.png --output project/out/sample.png --weights_AE model_logs/checkpoint.h5 --config_AE config/cloud_detection_config.yml --weights_GAN model_logs/SN_PatchGAN --config_GAN config/cloud_removal_config.yml 

Maybe you can give an advice to run it correctly? 
Thanks for help :D

**Comment by JerrySchonenberg** [comment]
Hi, the command looks fine to me. Would you happen to have an example?

Do note that the AE has some troubles detecting the edges of the clouds (i.e., not a recall of 1), which means that these edges are propagated by the SN-PatchGAN. See as reference the difference between CloudGAN (1) and CloudGAN (2) in the second figure of the README, in particular the bottom row. In similar fashion, this also applies to the shadows caused by the clouds, which were not included in the masks we used to train the AE.
